# frozen_string_literal: true

# Modulo de constantes do jogo
module PongConstants
  # Dados da tela
  WIDTH = 640
  HEIGHT = 480
  TITLE = 'Pong'
  MID = WIDTH / 2
  # Dados campo
  CAMP_BORDER = 5
  CAMP_LIMIT_X1 = CAMP_BORDER
  CAMP_LIMIT_X2 = WIDTH - CAMP_BORDER
  CAMP_LIMIT_Y1 = CAMP_BORDER
  CAMP_LIMIT_Y2 = HEIGHT - CAMP_BORDER
  CAMP_MID_LINE_X = MID
  CAMP_MID_LINE_WIDTH = 2
  CAMP_MID_LINE_HEIGHT = CAMP_LIMIT_Y2 - CAMP_BORDER
  CAMP_LINES_COLOR = [1, 1, 1, 0.5].freeze
  # Dados bola
  BALL_SPEED = 4
  BALL_RADIUS = 5
  BALL_POSITION_X = MID
  BALL_POSITION_Y = (CAMP_LIMIT_Y1..CAMP_LIMIT_Y2).freeze
  # Dados players
  PLAYER_SPEED = 3
  PLAYER_HEIGHT = 70
  PLAYER_WIDTH = 4
  PLAYER_POSITION_Y = (HEIGHT - PLAYER_HEIGHT) / 2
  PLAYER_SPACE = 10
  PLAYER1_POSITION_X = (PLAYER_SPACE - PLAYER_WIDTH / 2) + CAMP_BORDER
  PLAYER2_POSITION_X = (WIDTH - PLAYER_SPACE - PLAYER_WIDTH / 2) - CAMP_BORDER
  # Dados da tela de pause
  PAUSE_TEXT = 'PRESS SPACE'
  PAUSE_X = WIDTH / 2 - 68
  PAUSE_Y = HEIGHT - CAMP_BORDER - 30
  PAUSE_OPACITY = 0.5
  UNPAUSE_OPACITY = 1
  # Dados da pontuação
  SCORE_X = MID - 34
  SCORE_Y = CAMP_BORDER + 30
end
